// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIajKZlDoODhJFdSsvIfz1oK-YVaPljnA',
    appId: '1:648358045075:web:b4dd9b0d9083b3458db466',
    messagingSenderId: '648358045075',
    projectId: 'the-gg-mart',
    authDomain: 'the-gg-mart.firebaseapp.com',
    storageBucket: 'the-gg-mart.appspot.com',
    measurementId: 'G-B2R6SY26B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC736gS_uvgsqv-CLlLPaCEOsNQ7QSxsMw',
    appId: '1:648358045075:android:249edce7b7b3e1738db466',
    messagingSenderId: '648358045075',
    projectId: 'the-gg-mart',
    storageBucket: 'the-gg-mart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMpeeGtJt_KavjFEYMsBCjJIeiBMtO4a4',
    appId: '1:648358045075:ios:c2f325dc04fa40d18db466',
    messagingSenderId: '648358045075',
    projectId: 'the-gg-mart',
    storageBucket: 'the-gg-mart.appspot.com',
    iosBundleId: 'com.example.ggMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMpeeGtJt_KavjFEYMsBCjJIeiBMtO4a4',
    appId: '1:648358045075:ios:5c952ccd8473699d8db466',
    messagingSenderId: '648358045075',
    projectId: 'the-gg-mart',
    storageBucket: 'the-gg-mart.appspot.com',
    iosBundleId: 'com.example.ggMart.RunnerTests',
  );
}
